version: "3.9"
   
services:
  db:
    image: postgres:12
    env_file: .env
    
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db



# https://docs.docker.com/samples/django/
# vhgalvez@gmail.com